ccflags-y += -I$(srctree)/$(src)/../../../drivers/base

ifneq ($(filter m y,$(CONFIG_SX937X_USB_CAL)),)
	ccflags-y += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq ($(filter m y,$(CONFIG_SX937X_POWER_SUPPLY_ONLINE)),)
	ccflags-y += -DCONFIG_USE_POWER_SUPPLY_ONLINE
endif

ifneq ($(filter m y,$(CONFIG_SX937X_FLIP_CAL)),)
	ccflags-y += -DCONFIG_CAPSENSE_FLIP_CAL
endif

obj-$(CONFIG_SARSENSOR_SX937X) += sx937x_sar.o
