# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_MSM_NPU) += npu/
obj-$(CONFIG_MSM_GLOBAL_SYNX) += synx/
obj-$(CONFIG_MSM_CVP) += cvp/
obj-$(CONFIG_CAMERA_CCI_INTF) += camera/cam_sensor_module/cam_cci/
