ccflags-y += -I$(srctree)/$(src)/../mmi_charger

ifneq ($(filter m y,$(CONFIG_WIRELESS_CPS4035B)),)
	ccflags-y += -DWIRELESS_CPS4035B
endif

ifneq ($(filter m y,$(CONFIG_WIRELESS_CPS4019)),)
	ccflags-y += -DWIRELESS_CPS4019
endif

ifneq ($(filter m y,$(CONFIG_MSB_DEV)),)
	ccflags-y += -DMSB_DEV
endif

ifneq ($(filter m y,$(CONFIG_SWITCHEDCAP_DUMP)),)
	ccflags-y += -DSWITCHEDCAP_DUMP
endif

ifneq ($(filter m y,$(CONFIG_SKIP_QTI_CHARGER_CONFIRMAION)),)
	ccflags-y += -DSKIP_QTI_CHARGER_CONFIRMAION
endif

ifneq ($(filter m y,$(CONFIG_FUELGUAGE_DUMP)),)
	ccflags-y += -DFUELGUAGE_DUMP
endif

obj-$(CONFIG_QTI_GLINK_CHARGER) += qti_glink_charger.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../bm_adsp_ulog/$(GKI_OBJ_MODULE_DIR)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../mmi_charger/$(GKI_OBJ_MODULE_DIR)/Module.symvers
