# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/

obj-$(CONFIG_BM_ADSP_ULOG)	+= bm_adsp_ulog/
obj-$(CONFIG_USE_MMI_CHARGER)	+= mmi_charger/
obj-$(CONFIG_QTI_GLINK_CHARGER)	+= mmi_charger/qti_glink_charger/
obj-$(CONFIG_QPNP_ADAPTIVE_CHARGE)	+= qpnp_adaptive_charge/
