obj-$(CONFIG_TOUCHSCREEN_NT36xxx_HOSTDL_SPI_MMI) += nova_0flash_mmi.o
nova_0flash_mmi-y += nt36xxx.o
nova_0flash_mmi-y += nt36xxx_ext_proc.o
nova_0flash_mmi-y += nt36xxx_fw_update.o
nova_0flash_mmi-y += nt36xxx_mp_ctrlram.o

ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_0FLASH_MMI_ENABLE_DOUBLE_TAP)),)
	ccflags-y += -DNVT_SENSOR_EN
endif
ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_0FLASH_MMI_NOTIFY_TOUCH_STATE)),)
	ccflags-y += -DNVT_SET_TOUCH_STATE
endif

ifneq ($(filter m y,$(CONFIG_NOVA_TOUCH_LAST_TIME)),)
	ccflags-y += -DNVT_TOUCH_LAST_TIME
endif

ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_PANEL_NOTIFICATIONS)),)
	ccflags-y += -DNVT_CONFIG_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_DRM_PANEL)),)
	ccflags-y += -DNVT_CONFIG_DRM_PANEL
endif

ifneq ($(filter m y,$(CONFIG_TOUCH_PANEL_NOTIFICATIONS)),)
	ccflags-y += -DCONFIG_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_CHIP_VER_1)),)
	ccflags-y += -DNVT_CONFIG_CHIP_VER_1
endif

ifneq ($(filter m y,$(CONFIG_NOVA_ESD_ENABLE)),)
	ccflags-y += -DNVT_CONFIG_ESD_ENABLE
endif

ifneq ($(filter m y,$(CONFIG_NOVA_LCM_FAST_LIGHTUP)),)
	ccflags-y += -DLCM_FAST_LIGHTUP
endif

ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_0FLASH_MMI_STYLUS_PALM)),)
	ccflags-y += -DPALM_GESTURE
endif
ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_0FLASH_MMI_STYLUS_PALM_RANGE)),)
	ccflags-y += -DPALM_GESTURE_RANGE
endif
ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_0FLASH_MMI_PEN_NOTIFIER)),)
	ccflags-y += -DNOVATECH_PEN_NOTIFIER
endif
ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_EDGE_SUPPRESSION)),)
	ccflags-y += -DEDGE_SUPPRESSION
endif

ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	ccflags-y += -DCONFIG_BOARD_USES_DOUBLE_TAP_CTRL
endif

ifneq ($(filter m y, $(CONFIG_SPI_SM8450)),)
	ccflags-y += -DCONFIG_SPI_SM8450
endif

ifneq ($(filter m y,$(CONFIG_DRM_PANEL_NOTIFICATIONS)),)
    ccflags-y += -DCONFIG_DRM_PANEL_NOTIFICATIONS
endif
ifneq ($(filter m y,$(CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS)),)
    ccflags-y += -DCONFIG_DRM_PANEL_EVENT_NOTIFICATIONS
endif
ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
    ccflags-y += -DCONFIG_INPUT_TOUCHSCREEN_MMI
    nova_0flash_mmi-objs += nt36xxx_mmi_class.o

    ifneq ($(filter m y, $(CONFIG_TOUCHCLASS_MMI_MULTIWAY_UPDATE_FW)),)
        ccflags-y += -DTS_MMI_TOUCH_MULTIWAY_UPDATE_FW
    endif
endif

ifneq ($(filter m y,$(CONFIG_GTP_DDA_STYLUS)),)
    ccflags-y += -DCONFIG_MOTO_DDA_PASSIVESTYLUS
    nova_0flash_mmi-objs += moto_ts_dda.o
endif
