prod_list := devon
find_target := $(foreach find, $(prod_list), $(findstring $(find), $(TARGET_PRODUCT)))
find_target := $(strip $(find_target))
$(warning find_target=$(find_target))
ifneq ($(find_target),)
$(warning define SUPPORT_PIN_CTRL)
ccflags-y += -DSUPPORT_PIN_CTRL
endif

ifneq ($(filter m y,$(CONFIG_INPUT_MISC_FPC1020_SAVE_TO_CLASS_DEVICE)),)
	ccflags-y += -DCONFIG_INPUT_MISC_FPC1020_SAVE_TO_CLASS_DEVICE
endif

obj-$(CONFIG_FPC_FPS_MMI) += fpc1020_mmi.o
fpc1020_mmi-y += fpc1020_tee.o
