obj-$(CONFIG_TOUCHSCREEN_GOODIX_BRL) := goodix_brl_mmi.o
goodix_brl_mmi-objs := \
					goodix_brl_i2c.o \
					goodix_brl_spi.o \
					goodix_ts_core.o \
					goodix_brl_hw.o \
					goodix_cfg_bin.o \
					goodix_ts_utils.o \
					goodix_brl_fwupdate.o \
					goodix_ts_inspect.o \
					goodix_ts_tools.o \
					goodix_ts_config.o

ifneq ($(filter m y, $(CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS)),)
    ccflags-y += -DCONFIG_DRM_PANEL_EVENT_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_DRM_PANEL_NOTIFICATIONS)),)
    ccflags-y += -DCONFIG_DRM_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_TOUCHSCREEN_GOODIX_BRL_SPI)),)
    ccflags-y += -DCONFIG_TOUCHSCREEN_GOODIX_BRL_SPI
endif

ifneq ($(filter m y,$(CONFIG_GTP_FOD)),)
    ccflags-y += -DCONFIG_GTP_FOD
    goodix_brl_mmi-objs += goodix_ts_gesture_fod.o

    ifneq ($(filter m y,$(CONFIG_ENABLE_GTP_VIRTUAL_FOD)),)
        ccflags-y += -DCONFIG_ENABLE_GTP_VIRTUAL_FOD
    endif
else
    goodix_brl_mmi-objs += goodix_ts_gesture.o
endif

ifneq ($(filter m y,$(CONFIG_GTP_LIMIT_USE_SUPPLIER)),)
    ccflags-y += -DCONFIG_GTP_LIMIT_USE_SUPPLIER
endif

ifneq ($(filter m y,$(CONFIG_GTP_ENABLE_PM_QOS)),)
    ccflags-y += -DCONFIG_GTP_ENABLE_PM_QOS
endif

ifneq ($(filter m y,$(CONFIG_GOODIX_ESD_ENABLE)),)
    ccflags-y += -DCONFIG_GOODIX_ESD_ENABLE
endif

ifneq ($(filter m y,$(CONFIG_TARGET_BUILD_FACROTY)),)
    ccflags-y += -DGTP_SAVE_IN_CSV
endif

ifneq ($(filter m y,$(CONFIG_GTP_LAST_TIME)),)
    ccflags-y += -DCONFIG_GTP_LAST_TIME
endif

ifneq ($(filter m y,$(CONFIG_GTP_DDA_STYLUS)),)
    ccflags-y += -DCONFIG_GTP_DDA_STYLUS
    goodix_brl_mmi-objs += goodix_ts_dda.o
endif

ifneq ($(filter m y,$(CONFIG_MOTO_DDA_PASSIVE_STYLUS)),)
    ccflags-y += -DCONFIG_MOTO_DDA_PASSIVESTYLUS
endif

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
    ccflags-y += -DCONFIG_INPUT_TOUCHSCREEN_MMI
    goodix_brl_mmi-objs += goodix_ts_mmi.o
endif

ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	ccflags-y += -DCONFIG_BOARD_USES_DOUBLE_TAP_CTRL
endif

ifneq ($(filter m y,$(CONFIG_INPUT_GOODIX_MMI_ENABLE_PALM)),)
    ccflags-y += -DGOODIX_PALM_SENSOR_EN
endif

ifeq ($(TARGET_BUILD_VARIANT), userdebug)
ifneq ($(filter m y, $(CONFIG_GTP_GHOST_LOG_CAPTURE)),)
	ccflags-y += -DCONFIG_GTP_GHOST_LOG_CAPTURE
	goodix_brl_mmi-objs += goodix_ts_log_capture.o
endif
endif

ifneq ($(filter m y,$(CONFIG_ENABLE_GTP_PALM_CANCEL)),)
    ccflags-y += -DCONFIG_ENABLE_GTP_PALM_CANCEL
endif

ifneq ($(filter m y,$(CONFIG_GTP_ENABLE_TOUCH_PALM_BY_ID)),)
    ccflags-y += -DCONFIG_ENABLE_GTP_PALM_CANCEL_BY_ID
endif

ifneq ($(filter m y,$(CONFIG_INPUT_GTP_PASSIVE_PEN_NOTIFIER)),)
    ccflags-y += -DGTP_PEN_NOTIFIER
endif

ifneq ($(findstring _factory,$(TARGET_PRODUCT)),)
USE_TARGET_PRODUCT := $(strip $(subst _factory,, $(TARGET_PRODUCT)))
else
USE_TARGET_PRODUCT := $(TARGET_PRODUCT)
endif

ifneq ($(filter oneli, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_ONELI
else ifneq ($(filter hiphi, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_HIPHI
else ifneq ($(filter hiphic, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_HIPHIC
else ifneq ($(filter li, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_LI
else ifneq ($(filter eqs, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_EQS
else ifneq ($(filter tundra%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_TUNDRA
else ifneq ($(filter miami%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_MIAMI
else ifneq ($(filter rtwo%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_RTWO
else ifneq ($(filter ctwo%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_CTWO
else ifneq ($(filter arcfox%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_ARCFOX
else ifneq ($(filter bronco, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_BRONCO
else ifneq ($(filter felix, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DCONFIG_GTP_DISP_MODE
else ifneq ($(filter zeekr%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_ZEEKR
else ifneq ($(filter lynkco%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_LYNKCO
else ifneq ($(filter bangkk%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_BANGKK
else ifneq ($(filter eqe%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_EQE
else ifneq ($(filter boston%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_BOSTON
else ifneq ($(filter cusco%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_CUSCO
else ifneq ($(filter avatrn%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_AVATRN
else ifneq ($(filter malmo%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_MALMO
else ifneq ($(filter tank%, $(USE_TARGET_PRODUCT)), )
        ccflags-y += -DPRODUCT_TANK
endif
$(warning "william ccflags-y = $(ccflags-y)")
