ifneq ($(filter m y,$(CONFIG_EGIS_FPS_PANEL_NOTIFICATIONS)),)
    ccflags-y += -DCONFIG_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_MMI_RELAY)),)
    ccflags-y += -DMMI_RELAY_MODULE
endif

rbs_fod_mmi-y += etxxx_fp.o

obj-$(CONFIG_RBS_FOD_MMI) += rbs_fod_mmi.o
